
# Task Analysis {.appendix}

**I will preface saying that I changed my user guide project goal. Instead of going for compartmental models, I will be writing how to forecast data, including speaking on the drawbacks of two packages for Covid-19 data. The repository that I was originally working with was outdated and there were many issues with the code. I was unable to properly run it on my machine.**

Here are some questions to guide you through the process of doing a task analysis. You don't have to specifically answer each one of these (and some may not apply), but they should get you started thinking in the right direction. 

## What are the prerequisites, for both knowledge and e.g. software setup? 
The prerequisites include:
- Knowing how to filter data sets to get the proper data
- basic RStudio knowledge with potential debugging


## What are the basic requirements for any data that the method is used on? 
  - Are missing values allowed? *no*
  - Should the data be confined within a certain range? *nope, but more data allows for a better prediction*
  - Does the data have to be approximately normally distributed? *nope*

## What are the basic components of the task?
  - Open RStudio
  - Install packages
    - library(covid19.analytics)
    - library(dplyr)
    - library(lubridate)
    - library(ggplot2)
    - library(forecast)
    - library(readr)
    - library(skimr)
    - library(prophet)
  - change the date format using lubridate
  - create a new column in the dataset from previous ones
  - forecast new data
  - plot both on the same graph
  - compare forecasting between `prophet` and `forecast`

## What decisions does the user need to be prepared to make on the fly?
- They need to determine what dataset to use and how to accommodate for missing values if there are any.
## What questions should the user ask of the "first draft" of the product? What adjustments may need to be made?


## Additional Guidance 

Your check-in should answer these basic questions (and similar concerns that apply more directly to your topic). 

Once you've completed the check-in, you can use this section to jump-start an introduction/set-up/getting started section in your user guide. 
This document should remain as an appendix to your main report. 
