# Infectious Disease Modeling using Compartment Models in R

For the scope, I plan to write a user guide that goes through how to set up a compartment model in R. I would have to research the packages that could be used and find a data set in order to provide an example of how to set up the model. Potentially, I could simulate a data set, but more research would be needed to figure out what data would need to be simulated. 

A compartment model would use the following differential equations that model the SEIR (susceptible, exposed, infectious, recovered) framework. 

$$\frac{dS(t)}{dt}=-\beta\frac{S(t)I(t)}{N},$$
$$\frac{dI(t)}{dt}=\beta\frac{S(t)I(t)}{N}-\sigma E(t),$$
$$\frac{dI(t)}{dt}=\sigma E(t)-\gamma I(t),$$
$$\frac{dR(t)}{dt}=\gamma I(t),$$

One interesting topic that I could consider is using COVID-19 data as one of the referenced articles used SAPHIRE, a different compartmental model, to simulate the spread of COVID-19 in Wuhan, Singapore. The data was made available in the article found [here](https://github.com/chaolongwang/SAPHIRE). Their code for their model is found [here](https://github.com/chaolongwang/SAPHIRE) as well, only needing modifications to fit the simpler SEIR framework.